-- Comments from: https://marmelab.com/blog/2017/01/09/sirene-import-sql.html
CREATE TABLE sirene_data (
    `siren` INT(9) UNSIGNED NOT NULL KEY COMMENT "Identifiant de l’entreprise",
    `nic` SMALLINT(5) UNSIGNED NOT NULL KEY COMMENT "Numéro interne de classement de l'établissement",
    `siret` BIGINT(10) UNSIGNED NOT NULL PRIMARY KEY COMMENT "Identifiant de l’entreprise",
    `statutDiffusionEtablissement` ENUM('O') NOT NULL COMMENT "Statut de diffusion de l’établissement",
    `dateCreationEtablissement` VARCHAR(10) NOT NULL KEY COMMENT "Date de création de l’entreprise",
    `trancheEffectifsEtablissement` ENUM('NN', '00', '01', '02', '03', '11', '12', '21', '22', '31', '32', '41', '42', '51', '52', '53') NOT NULL KEY COMMENT "Tranche d’effectif salarié de l’établissement",
    `anneeEffectifsEtablissement` VARCHAR(4) NOT NULL COMMENT "Année de validité de la tranche d’effectif salarié de l’établissement",
    `activitePrincipaleRegistreMetiersEtablissement` VARCHAR(6) NOT NULL KEY COMMENT "Activité exercée par l’artisan inscrit au registre des métiers",
    `dateDernierTraitementEtablissement` VARCHAR(10) NULL COMMENT "Date du dernier traitement de l’établissement dans le répertoire Sirene",
    `etablissementSiege` ENUM('true', 'false') NOT NULL KEY COMMENT "Qualité de siège ou non de l’établissement",
    `nombrePeriodesEtablissement` TINYINT(2) NOT NULL COMMENT "Nombre de périodes de l’établissement",
    `complementAdresseEtablissement` VARCHAR(38) NULL COMMENT "Complément d’adresse",
    `numeroVoieEtablissement` VARCHAR(1) NOT NULL COMMENT "Indice de répétition dans la voie",
    `indiceRepetitionEtablissement` VARCHAR(1) NULL COMMENT "Indice de répétition dans la voie",
    `typeVoieEtablissement` ENUM('ALL', 'AV', 'BD', 'CAR', 'CHE', 'CHS', 'CITE', 'COR', 'CRS', 'DOM', 'DSC', 'ECA', 'ESP', 'FG', 'GR', 'HAM', 'HLE', 'IMP', 'LD', 'LOT', 'MAR', 'MTE', 'PAS', 'PL', 'PLN', 'PLT', 'PRO') NOT NULL COMMENT "Type de voie",
    `libelleVoieEtablissement` VARCHAR(100) NULL COMMENT "Libellé de voie",
    `codePostalEtablissement` VARCHAR(5) NOT NULL KEY COMMENT "Code postal",
    `libelleCommuneEtablissement` VARCHAR(100) NOT NULL COMMENT "Libellé de la commune",
    `libelleCommuneEtrangerEtablissement` VARCHAR(100) NOT NULL COMMENT "Libellé de la commune pour un établissement situé à l’étranger",
    `distributionSpecialeEtablissement` VARCHAR(26) NULL COMMENT "Distribution spéciale de l’établissement",
    `codeCommuneEtablissement` VARCHAR(5) NOT NULL KEY COMMENT "Code commune de l’adresse secondaire",
    `codeCedexEtablissement` VARCHAR(9) NULL KEY COMMENT "Code cedex",
    `libelleCedexEtablissement` VARCHAR(100) NOT NULL COMMENT "Libellé du code cedex",
    `codePaysEtrangerEtablissement` VARCHAR(5) NOT NULL COMMENT "Code pays pour un établissement situé à l’étranger",
    `libellePaysEtrangerEtablissement` VARCHAR(100) NOT NULL COMMENT "Libellé du pays pour un établissement situé à l’étranger",
    `complementAdresse2Etablissement` VARCHAR(38) NULL COMMENT "Complément d’adresse secondaire",
    `numeroVoie2Etablissement` VARCHAR(4) NOT NULL COMMENT "Numéro de la voie de l’adresse secondaire",
    `indiceRepetition2Etablissement` VARCHAR(1) NULL COMMENT "Indice de répétition dans la voie pour l’adresse secondaire",
    `typeVoie2Etablissement` ENUM('ALL', 'AV', 'BD', 'CAR', 'CHE', 'CHS', 'CITE', 'COR', 'CRS', 'DOM', 'DSC', 'ECA', 'ESP', 'FG', 'GR', 'HAM', 'HLE', 'IMP', 'LD', 'LOT', 'MAR', 'MTE', 'PAS', 'PL', 'PLN', 'PLT', 'PRO') NOT NULL COMMENT "Type de voie de l’adresse secondaire",
    `libelleVoie2Etablissement` VARCHAR(100) NULL COMMENT "Libellé de voie de l’adresse secondaire",
    `codePostal2Etablissement` VARCHAR(5) NOT NULL KEY COMMENT "Code postal de l’adresse secondaire",
    `libelleCommune2Etablissement` VARCHAR(100) NOT NULL COMMENT "Libellé de la commune de l’adresse secondaire",
    `libelleCommuneEtranger2Etablissement` VARCHAR(100) NOT NULL COMMENT "Libellé de la commune de l’adresse secondaire pour un établissement situé à l’étranger",
    `distributionSpeciale2Etablissement` VARCHAR(26) NULL COMMENT "Distribution spéciale de l’adresse secondaire de l’établissement",
    `codeCommune2Etablissement` VARCHAR(5) NOT NULL KEY COMMENT "Code commune de l’adresse secondaire",
    `codeCedex2Etablissement` VARCHAR(9) NULL COMMENT "Code cedex de l’adresse secondaire",
    `libelleCedex2Etablissement` VARCHAR(100) NOT NULL COMMENT "Libellé du code cedex de l’adresse secondaire",
    `codePaysEtranger2Etablissement` VARCHAR(5) NOT NULL COMMENT "Code pays de l’adresse secondaire pour un établissement situé à l’étranger",
    `libellePaysEtranger2Etablissement` VARCHAR(100) NOT NULL COMMENT "Libellé du pays de l’adresse secondaire pour un établissement situé à l’étranger",
    `dateDebut` VARCHAR(10) NOT NULL COMMENT "Date de début d'une période d'historique d'un établissement",
    `etatAdministratifEtablissement` ENUM("A", "F") NOT NULL KEY COMMENT "État administratif de l’établissement",
    `enseigne1Etablissement` VARCHAR(50) NOT NULL KEY COMMENT "Première ligne d’enseigne de l’établissement",
    `enseigne2Etablissement` VARCHAR(50) NOT NULL KEY COMMENT "Deuxième ligne d’enseigne de l’établissement",
    `enseigne3Etablissement` VARCHAR(50) NOT NULL KEY COMMENT "Troisième ligne d’enseigne de l’établissement",
    `denominationUsuelleEtablissement` VARCHAR(100) NOT NULL COMMENT "Dénomination usuelle de l’établissement",
    `activitePrincipaleEtablissement` VARCHAR(6) NOT NULL KEY COMMENT "Activité principale de l'établissement pendant la période",
    `nomenclatureActivitePrincipaleEtablissement` ENUM('NAFRev2', 'NAFRev1', 'NAF1993', 'NAP') NOT NULL KEY COMMENT "Nomenclature d’activité de la variable activitePrincipaleEtablissement",
    `caractereEmployeurEtablissement` ENUM('O', 'N') NULL KEY COMMENT "Caractère employeur de l’établissement"
);