CREATE TABLE Sirene.unitelegale(
siren CHAR(9) NOT NULL COMMENT "Numéro Siren",
dateCreationUniteLegale DATE NOT NULL DEFAULT '0000-00-00' COMMENT "Date de création de l'unité légale",
prenom1UniteLegale CHAR(20) COMMENT "Premier prénom déclaré pour un personne physique",
prenom2UniteLegale CHAR(20) COMMENT "Deuxième prénom déclaré pour un personne physique",
prenom3UniteLegale CHAR(20) COMMENT "Troisième prénom déclaré pour un personne physique",
prenom4UniteLegale CHAR(20) COMMENT "Quatrième prénom déclaré pour un personne physique",
prenomUsuelUniteLegale CHAR(20) COMMENT "Prénom usuel de la personne physique",
identifiantAssociationUniteLegale CHAR(10) COMMENT "Numéro au Répertoire National des Associations",
trancheEffectifsUniteLegale CHAR(2) NOT NULL COMMENT "Tranche d’effectif salarié de l’unité légale",
anneeEffectifsUniteLegale YEAR NOT NULL DEFAULT '0000' COMMENT "Année de validité de la tranche d’effectif salarié de l’unité légale",
dateDernierTraitementUniteLegale DATE NOT NULL DEFAULT '0000-00-00' COMMENT "Date du dernier traitement de l’unité légale dans le répertoire Sirene",
categorieEntreprise CHAR(3) COMMENT "Catégorie à laquelle appartient l’entreprise",
anneeCategorieEntreprise YEAR NOT NULL DEFAULT '0000' COMMENT "Année de validité de la catégorie d’entreprise",
dateDebut DATE NOT NULL DEFAULT '0000-00-00' COMMENT "Date de début d'une période d'historique d'une unité légale",
etatAdministratifUniteLegale CHAR(1) COMMENT "État administratif de l’unité légale",
nomUniteLegale CHAR(100) COMMENT "Nom de naissance de la personnes physique",
nomUsageUniteLegale CHAR(100) COMMENT "Nom d’usage de la personne physique",
denominationUniteLegale CHAR(120) COMMENT "Dénomination de l’unité légale",
denominationUsuelle1UniteLegale CHAR(70) COMMENT "Dénomination usuelle de l’unité légale",
denominationUsuelle2UniteLegale CHAR(70) COMMENT "Dénomination usuelle de l’unité légale – deuxième champ",
denominationUsuelle3UniteLegale CHAR(70) COMMENT "Dénomination usuelle de l’unité légale – troisième champ",
categorieJuridiqueUniteLegale CHAR(4) COMMENT "Catégorie juridique de l’unité légale",
activitePrincipaleUniteLegale CHAR(6) COMMENT "Activité principale de l’unité légale",
nomenclatureActivitePrincipaleUniteLegale CHAR(8) COMMENT "Nomenclature d’activité de la variable activitePrincipaleUniteLegale",
nicSiegeUniteLegale CHAR(5) COMMENT "Numéro interne de classement (Nic) de l’unité légale",
caractereEmployeurUniteLegale TINYINT NOT NULL DEFAULT -1 COMMENT "Caractère employeur de l’unité légale",
PRIMARY KEY (siren) ,
INDEX siren (siren ASC) VISIBLE ,
INDEX dateCreationUniteLegale (dateCreationUniteLegale ASC) VISIBLE ,
INDEX trancheEffectifsUniteLegale (trancheEffectifsUniteLegale ASC) VISIBLE ,
INDEX categorieEntreprise (categorieEntreprise ASC) VISIBLE ,
INDEX nomUniteLegale (nomUniteLegale ASC) VISIBLE ,
INDEX nomUsageUniteLegale (nomUsageUniteLegale ASC) VISIBLE ,
INDEX denominationUniteLegale (denominationUniteLegale ASC) VISIBLE ,
INDEX denominationUsuelle1UniteLegale (denominationUsuelle1UniteLegale ASC) VISIBLE ,
INDEX denominationUsuelle2UniteLegale (denominationUsuelle2UniteLegale ASC) VISIBLE ,
INDEX denominationUsuelle3UniteLegale (denominationUsuelle3UniteLegale ASC) VISIBLE ,
INDEX categorieJuridiqueUniteLegale (categorieJuridiqueUniteLegale ASC) VISIBLE ,
INDEX activitePrincipaleUniteLegale (activitePrincipaleUniteLegale ASC) VISIBLE ,
INDEX nicSiegeUniteLegale (nicSiegeUniteLegale ASC) VISIBLE ,
INDEX caractereEmployeurUniteLegale (caractereEmployeurUniteLegale ASC) VISIBLE );