LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_159.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_159.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_160.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_160.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_161.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_161.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_162.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_162.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_163.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_163.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_164.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_164.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_165.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_165.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_166.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_166.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_167.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_167.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_168.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_168.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_169.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_169.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_170.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_170.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_171.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_171.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_172.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_172.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_173.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_173.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_174.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_174.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_175.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_175.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_176.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_176.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_177.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_177.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_178.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_178.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_179.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_179.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_180.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_180.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_181.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_181.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_182.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_182.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_183.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_183.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_184.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_184.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_185.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_185.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_186.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_186.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_187.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_187.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_188.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_188.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_189.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_189.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_190.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_190.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_191.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_191.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_192.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_192.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_193.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_193.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_194.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_194.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_195.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_195.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_196.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_196.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_197.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_197.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_198.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_198.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_199.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_199.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_200.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_200.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_201.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_201.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_202.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_202.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_203.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_203.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_204.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_204.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_205.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_205.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_206.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_206.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_207.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_207.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_208.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_208.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_209.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_209.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_210.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_210.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_211.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_211.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_212.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_212.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_213.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_213.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_214.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_214.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_215.csv' INTO TABLE unitelegale CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\unite\\court\\StockUniteLegale_utf8_court_215.csv';
