LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_1.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_1.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_2.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_2.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_3.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_3.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_4.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_4.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_5.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_5.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_6.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_6.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_7.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_7.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_8.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_8.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_9.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_9.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_10.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_10.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_11.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_11.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_12.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_12.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_13.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_13.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_14.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_14.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_15.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_15.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_16.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_16.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_17.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_17.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_18.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_18.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_19.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_19.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_20.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_20.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_21.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_21.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_22.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_22.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_23.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_23.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_24.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_24.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_25.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_25.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_26.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_26.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_27.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_27.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_28.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_28.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_29.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_29.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_30.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_30.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_31.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_31.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_32.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_32.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_33.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_33.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_34.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_34.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_35.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_35.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_36.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_36.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_37.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_37.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_38.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_38.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_39.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_39.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_40.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_40.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_41.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_41.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_42.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_42.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_43.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_43.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_44.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_44.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_45.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_45.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_46.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_46.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_47.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_47.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_48.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_48.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_49.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_49.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_50.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_50.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_51.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_51.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_52.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_52.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_53.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_53.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_54.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_54.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_55.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_55.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_56.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_56.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_57.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_57.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_58.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_58.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_59.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_59.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_60.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_60.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_61.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_61.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_62.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_62.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_63.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_63.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_64.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_64.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_65.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_65.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_66.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_66.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_67.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_67.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_68.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_68.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_69.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_69.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_70.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_70.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_71.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_71.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_72.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_72.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_73.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_73.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_74.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_74.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_75.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_75.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_76.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_76.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_77.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_77.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_78.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_78.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_79.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_79.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_80.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_80.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_81.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_81.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_82.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_82.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_83.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_83.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_84.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_84.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_85.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_85.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_86.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_86.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_87.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_87.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_88.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_88.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_89.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_89.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_90.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_90.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_91.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_91.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_92.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_92.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_93.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_93.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_94.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_94.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_95.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_95.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_96.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_96.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_97.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_97.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_98.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_98.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_99.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_99.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_100.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_100.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_101.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_101.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_102.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_102.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_103.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_103.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_104.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_104.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_105.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_105.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_106.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_106.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_107.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_107.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_108.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_108.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_109.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_109.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_110.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_110.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_111.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_111.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_112.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_112.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_113.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_113.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_114.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_114.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_115.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_115.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_116.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_116.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_117.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_117.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_118.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_118.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_119.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_119.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_120.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_120.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_121.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_121.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_122.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_122.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_123.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_123.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_124.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_124.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_125.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_125.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_126.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_126.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_127.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_127.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_128.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_128.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_129.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_129.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_130.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_130.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_131.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_131.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_132.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_132.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_133.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_133.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_134.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_134.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_135.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_135.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_136.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_136.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_137.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_137.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_138.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_138.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_139.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_139.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_140.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_140.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_141.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_141.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_142.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_142.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_143.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_143.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_144.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_144.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_145.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_145.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_146.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_146.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_147.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_147.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_148.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_148.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_149.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_149.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_150.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_150.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_151.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_151.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_152.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_152.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_153.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_153.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_154.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_154.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_155.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_155.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_156.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_156.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_157.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_157.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_158.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_158.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_159.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_159.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_160.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_160.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_161.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_161.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_162.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_162.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_163.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_163.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_164.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_164.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_165.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_165.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_166.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_166.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_167.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_167.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_168.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_168.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_169.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_169.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_170.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_170.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_171.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_171.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_172.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_172.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_173.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_173.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_174.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_174.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_175.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_175.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_176.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_176.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_177.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_177.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_178.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_178.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_179.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_179.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_180.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_180.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_181.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_181.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_182.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_182.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_183.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_183.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_184.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_184.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_185.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_185.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_186.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_186.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_187.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_187.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_188.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_188.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_189.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_189.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_190.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_190.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_191.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_191.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_192.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_192.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_193.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_193.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_194.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_194.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_195.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_195.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_196.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_196.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_197.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_197.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_198.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_198.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_199.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_199.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_200.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_200.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_201.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_201.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_202.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_202.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_203.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_203.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_204.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_204.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_205.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_205.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_206.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_206.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_207.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_207.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_208.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_208.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_209.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_209.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_210.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_210.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_211.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_211.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_212.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_212.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_213.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_213.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_214.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_214.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_215.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_215.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_216.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_216.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_217.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_217.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_218.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_218.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_219.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_219.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_220.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_220.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_221.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_221.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_222.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_222.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_223.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_223.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_224.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_224.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_225.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_225.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_226.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_226.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_227.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_227.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_228.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_228.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_229.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_229.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_230.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_230.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_231.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_231.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_232.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_232.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_233.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_233.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_234.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_234.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_235.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_235.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_236.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_236.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_237.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_237.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_238.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_238.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_239.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_239.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_240.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_240.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_241.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_241.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_242.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_242.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_243.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_243.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_244.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_244.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_245.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_245.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_246.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_246.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_247.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_247.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_248.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_248.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_249.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_249.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_250.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_250.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_251.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_251.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_252.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_252.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_253.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_253.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_254.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_254.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_255.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_255.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_256.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_256.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_257.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_257.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_258.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_258.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_259.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_259.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_260.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_260.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_261.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_261.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_262.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_262.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_263.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_263.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_264.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_264.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_265.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_265.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_266.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_266.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_267.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_267.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_268.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_268.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_269.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_269.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_270.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_270.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_271.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_271.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_272.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_272.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_273.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_273.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_274.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_274.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_275.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_275.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_276.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_276.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_277.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_277.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_278.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_278.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_279.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_279.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_280.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_280.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_281.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_281.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_282.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_282.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_283.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_283.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_284.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_284.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_285.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_285.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_286.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_286.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_287.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_287.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_288.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_288.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_289.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_289.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_290.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_290.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_291.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_291.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_292.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_292.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_293.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_293.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_294.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_294.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_295.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_295.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_296.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_296.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_297.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_297.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_298.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_298.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_299.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_299.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_300.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_300.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_301.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_301.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_302.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_302.csv';
LOAD DATA LOCAL INFILE  'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_303.csv' INTO TABLE etablissement CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
\! echo 'D:\\Mysql\\etablissement\\court\\StockEtablissement_utf8_court_303.csv';
